[package]
name = "ggez-test"
version = "0.1.0"
authors = ["Carl Öst Wilkens <carl@ostwilkens.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
rand = "0.7.2"
mint = "0.5.3"